/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Event = IDL.Record({
  'date' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Facility = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MembershipTier = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'priceInINR' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
  'getMembershipTiers' : IDL.Func([], [IDL.Vec(MembershipTier)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Event = IDL.Record({
    'date' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Facility = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const MembershipTier = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'priceInINR' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
    'getMembershipTiers' : IDL.Func([], [IDL.Vec(MembershipTier)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };